### ISSUE TITLE
Missing Inventory in Indexers List

### ISSUE THREAD

**Issue by sedonik** [AdobeDocs/commerce-php#178]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What's missing?

In the Indexers List at page https://developer.adobe.com/commerce/php/development/components/indexing/#indexers 
Inventory Indexer is missed:

INDEXER METHOD NAME: inventory
INDEXER CLASS: [Magento\InventoryIndexer\Indexer\Mview\Action](https://github.com/magento/inventory/blob/develop/InventoryIndexer/Indexer/Mview/Action.php) 
DESCRIPTION:  Provides indexation logic for Inventory Management

**Comment by pawan** [comment]
@magento-docs @magento I am working on this

**Comment by pawan** [comment]
@jeff-matthews created PR https://github.com/AdobeDocs/commerce-php/pull/219

**Comment by jeff-matthews** [comment]
Thanks @pawan!
