### ISSUE TITLE
On Private Content page, invalid link

### ISSUE THREAD

**Issue by kallie-e** [AdobeDocs/commerce-php#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://developer.adobe.com/commerce/php/development/cache/page/private-content/#cacheable-page-checklist

### What's wrong with the content?

Under "Cacheable page checklist", the last bullet point, the link to "context variable" navigates to "Error 404: Page not found"

### What changes do you propose?

Update the url to the appropriate existing page that discusses declaring a custom context variable.

I *think* this might be this link.  Please verify first:
https://developer.adobe.com/commerce/php/development/cache/page/public-content/#configure-page-variations

### Anything else that can help to cover this?

Not that I can think of.

**Comment by jeff-matthews** [comment]
Thanks for the report @kallie-e!

You're right, the link should be: https://developer.adobe.com/commerce/php/development/cache/page/public-content/#configure-page-variations

Do you want to open a pull request to update that?

**Comment by jeff-matthews** [comment]
Since the fix is a little nuanced, I decided to open a PR.

> _**Note to self/team**: You must use absolute links within include files._
