### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by jeros-tbd** [AdobeDocs/commerce-php#62]
Issue in /src/pages/development/components/message-queues/bulk-operations-example.md

end of file : replace 

> As a result, if AMQP is configured in the deployment configuration of the queue, you can omit connection declarations in the queue_customer.xml,

by 

> As a result, if AMQP is configured in the deployment configuration of the queue, you can omit connection declarations in the queue_consumer.xml,

**Comment by chakravarthykalyan90** [comment]
Hi @jeros-tbd this is taken care.

**Comment by jeff-matthews** [comment]
Fixed in #87
